.MODEL SMALL
.STACK 100H
.DATA
  MSG1 DB 10,13,"INPUT A CHARACTER: $"
  MSG2 DB 10,13,"THIS CHARACTER IN LOWER CASE LANGUAGE: $"
  MSG3 DB 10,13,"THIS CHARACTER IN UPPERCASE LANGUAGE: $"
  MSG_IN DB 10,13,"INVALID CHARACTER $"
  
  AGAIN_MSG DB 10,13,"DO YOU WANT TO DO IT AGAIN? Y/N: $"
  ALL_CH DB 10,13,"ALL CHARACTER: $"  
  CHARACTER DB ?
  
  CHR DB ?
  
  .CODE
  MAIN PROC
    MOV AX,@DATA
    MOV DS,AX 
    
    START:
    LEA DX,MSG1
    MOV AH,9
    INT 21H
    
    MOV AH,1
    INT 21H
    MOV CHR,AL
    
    CMP CHR,65
    JGE CHK_UPPERCASE
    JL INVALID:
    
    CHK_UPPERCASE:
    CMP CHR,90
    JLE DIS_UPPER:
    JG CHK_LOWERCASE:
    
    CHK_LOWERCASE:
    CMP CHR,97
    JGE CHK_LOWERCASE2: 
    JL INVALID:
    
    CHK_LOWERCASE2: 
    CMP CHR,122
    JLE DIS_LOWER:
    JG INVALID:
    
    DIS_UPPER:
    LEA DX,MSG2
    MOV AH,9
    INT 21H 
    
    MOV AH,2
    MOV DL,CHR
    ADD DL,20H
    INT 21H
    JMP AGAIN:  
    
    DIS_LOWER:
    LEA DX,MSG3
    MOV AH,9
    INT 21H 
    
    MOV AH,2
    MOV DL,CHR
    SUB DL,20H
    INT 21H
    JMP AGAIN:
    
    
   INVALID:
   LEA DX,MSG_IN
   MOV AH,9
   INT 21H 
   
   AGAIN:
   LEA DX,AGAIN_MSG
   MOV AH,9
   INT 21H
   
   MOV AH,1
   INT 21H
   MOV DL,AL
   CMP DL,'Y'
   JE START:  
   
   LEA DX,ALL_CH
   MOV AH,9
   INT 21H   
   
   MOV CHARACTER,65
   MOV CH,65 
   TOP:
   MOV AH,2
   MOV DL,CHARACTER
   INT 21H  
   ADD DL,20H
   INT 21H
   MOV DL,20H
   INT 21H
   
   INC CHARACTER
   CMP CHARACTER,90
   JLE TOP:   
    
   
   
    
   EXIT: 
   MOV AH,4CH
   INT 21H
   MAIN ENDP
  END MAIN